"""
This type stub file was generated by pyright.
"""

"""This file defines MIDI standard constants, which are useful for converting
between numeric MIDI data values and human-readable text.

"""
INSTRUMENT_MAP = ...
INSTRUMENT_CLASSES = ...
DRUM_MAP = ...
